Algoritmo "Calculadora"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/01/2025
Var
// Seção de Declarações das variáveis 
N1, N2, S: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("digite um número: ")
Leia (N1)
escreva ("digite outro número: ")
Leia (N2)
escreva ("O valor a seguir é: ")
S <- N1 / N2
escreva (S)

Fimalgoritmo