Algoritmo "par ou impar"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2025
Var
   // Seção de Declarações das variáveis
   n: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("coloque um número: ")
   leia(n)
   se(n % 2 = 0) entao
      escreval("o valor é par")
   senao
      escreval("o valor será impar")
   fimse

Fimalgoritmo