Algoritmo "porcentagem"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/01/2025
Var
// Seção de Declarações das variáveis 
   v, x: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("coloque o valor em porcento para sabermos quanto eu vale")
   leia(v)
   x <- abs(v*60)/100)
   escreva("o resultado é ", x)
Fimalgoritmo