Algoritmo "Soma parametro referencia"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/01/2025
Var
// Seção de Declarações das variáveis 
   x,y: inteiro


procedimento soma(var a,b: inteiro)
inicio

  a <- a + 1
  b <- b + 2
  escreva("A soma vale ", a + b)

fimprocedimento
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

   x <- 5
   y <- 8
   soma(x, y)
   escreva(x,y)


Fimalgoritmo